### ISSUE TITLE
Console error "Cannot read property 'registry' of undefined"

### ISSUE THREAD

**Issue by jefflau** [jefflau/ens-manager#28]
Reddit comment:

When I start typing and I enter a '.', the first error appears:

ens.js:698 Uncaught (in promise) TypeError: Cannot read property 'registry' of undefined
    at _callee2$ (https://manager.ens.domains/static/js/main.48b587ac.js:19517:74)
    at tryCatch (https://manager.ens.domains/static/js/main.48b587ac.js:65153:41)
    at Generator.invoke [as _invoke] (https://manager.ens.domains/static/js/main.48b587ac.js:65391:23)
    at Generator.prototype.(anonymous function) [as next] (https://manager.ens.domains/static/js/main.48b587ac.js:65205:22)
    at step (https://manager.ens.domains/static/js/main.48b587ac.js:18938:192)
    at https://manager.ens.domains/static/js/main.48b587ac.js:18938:362
    at <anonymous>
Then, when I hit 'Get details', after a second or two, the exact same error appears in the console.

https://www.reddit.com/r/ethereum/comments/6j1k78/first_beta_release_of_the_ens_manager_app_manage/djb9d08/?st=j4bk0h6s&sh=2429f468

**Comment by jefflau** [comment]
Issue was related to the user using metamask and the parity chrome plugin at the same time without the core parity application actually running. User needed to turn off parity to stop the web3 object from being overwritten.
